---
name: my_movie
description: Movie Reccomendation
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_riverpod: ^2.1.3
  dio: ^4.0.6
  multiple_result: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/
