---
name: my_movie
description: Movie Recommendation
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_riverpod: ^2.1.3
  dio: ^4.0.6
  multiple_result: ^4.0.0
  flutter_launcher_icons: ^0.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
flutter_icons:
  android: true
  image_path_android: "assets/images/app_icon.png"
flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
